"""
Django settings for device_config_backup project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5_gab0w!9la&ft2t^96-g20y^%5-=50jds4ubadcj=a*c9n-id'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'device_config_operator.apps.DeviceConfigOperatorConfig',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'device_config_backup.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': ['./templates'],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'device_config_backup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DEVICE_CONFIG_BACKUP_DB_NAME = os.environ.get('DEVICE_CONFIG_BACKUP_DB_NAME', 'device_config_backup')
DEVICE_CONFIG_BACKUP_DB_USER_NAME = os.environ.get('DEVICE_CONFIG_BACKUP_DB_USER_NAME', 'device_config_backup')
DEVICE_CONFIG_BACKUP_DB_PASSWORD = os.environ.get('DEVICE_CONFIG_BACKUP_DB_PASSWORD', 'device_config_backup')
DEVICE_CONFIG_BACKUP_HOST_ADDRESS = os.environ.get('DEVICE_CONFIG_BACKUP_HOST_ADDRESS', 'device_config_backup_host_address')

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql_psycopg2',
		'NAME': DEVICE_CONFIG_BACKUP_DB_NAME,
		'USER': DEVICE_CONFIG_BACKUP_DB_USER_NAME,
		'PASSWORD': DEVICE_CONFIG_BACKUP_DB_PASSWORD,
		'HOST': DEVICE_CONFIG_BACKUP_HOST_ADDRESS,
		'PORT': '5432',
	}
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Yakutsk'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

FERNET_KEYS = [
	'SuperStromng encrPton string',
]

AMQP_EXCHANGE_DEVICE_CONFIG_OPERATOR = os.environ.get('RMQ_TELNET_OPERATOR_RMQ_EXCHANGE', '')
AMQP_QUEUE_DEVICE_CONFIG_UPDATE_REQUESTS = os.environ.get('RMQ_TELNET_OPERATOR_RMQ_QUEUE_IN', '')

AMQP_EXCHANGE_NETWORK = os.environ.get('RMQ_PING_COMMANDER_RMQ_EXCHANGE', '')
AMQP_QUEUE_IP_ADRRESS_PING_REQUEST = os.environ.get('RMQ_PING_OPERATOR_RMQ_QUEUE_IN', '')