version: '3'
services:

  rabbitmq:
    image: "rabbitmq:3.6-management"
    container_name: rmq
    ports:
      - "5671:5671/tcp"
      - "5672:5672/tcp"
      - "15671:15671/tcp"
      - "25672:25672/tcp"
      - "15672:15672/tcp"
    networks:
      - rmq_net

  device_config_backup:
    build: /tmp/device_config_backup/
    # build:
    #   context: /tmp/device_config_backup/
    ports:
      - "8809:8809/tcp"
      - "8809:8809/udp"
    container_name: d_c_b
    # restart: always
    depends_on:
      - rabbitmq
    networks:
      - rmq_net  

  rmq_postgres_comander:
    build: /tmp/rmq_postgres_commander/
    restart: always
    container_name: d_c_b_pgc
    depends_on:
      - rabbitmq
    networks:
      - rmq_net  

  rmq_telnet_operator:
    build: /tmp/rmq_telnet_operator/
    restart: always
    container_name: d_c_b_to
    depends_on:
      - rabbitmq
    networks:
      - rmq_net 

  rmq_ping_comander:
    build: /tmp/rmq_ping_commander/
    restart: always
    container_name: d_c_b_pc
    depends_on:
      - rabbitmq
    networks:
      - rmq_net       

networks:
  rmq_net:      