version: '3'
services:

  rabbitmq:
    image: "rabbitmq:3.6-management"
    # image: "rabbitmq:3.7.26-management-alpine"
    ports:
      - "5671:5671/tcp"
      - "5672:5672/tcp"
      - "15671:15671/tcp"
      - "25672:25672/tcp"
      - "15672:15672/tcp"
      # - "4369:4369/tcp"
    networks:
      - rmq_net

  device_config_operator:
    build: device_config_operator/
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - rmq_net  

  rmq_postgres_comander:
    build: ../rmq_postgres_comander/
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - rmq_net  

  rmq_telnet_operator:
    build: ../rmq_telnet_comander/
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - rmq_net 

  rmq_ping_comander:
    build: ../rmq_ping_comander/
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - rmq_net       

networks:
  rmq_net:      