# Generated by Django 2.0.7 on 2018-07-31 01:50

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('device_config_operator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_username',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
