# Generated by Django 2.0.7 on 2018-08-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_config_operator', '0002_auto_20180731_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='device_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
