# Generated by Django 2.0.7 on 2018-08-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_config_operator', '0003_deviceconfig_device_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(default='Unknown', max_length=100, unique=True)),
                ('network', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
